name: ClientWorker 
catch_rules:
    - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|unpkg\.com|npm\.elemecdn\.com)
      transform_rules:
      - search: _
        replace:
          - _
          - https://unpkg.com
          - https://fastly.jsdelivr.net/npm
          - https://unpkg.zhimg.com 
          - https://npm.elemecdn.com 
          - https://npm.sourcegcdn.com 
          - https://cdn.bilicdn.tk/npm 
        action: fetch
        fetch:
          preflight: false
          engine: parallel
    - rule: .*
      transform_rules:
      - search: .*
        action: skip     #? 2.8.1新增，跳过cw规则
        
      
