name: ClientWorker
catch_rules:
    - rule: _
      transform_rules:
        - search: \#.*
          replace: ''
        - search: \?.*
          replace: '' 
        - search: _ 
          replace: 
          - _
          - example.com #替換這裡的地址
          action: fetch
          fetch:
            status: 200
            engine: parallel
            preflight: false
            timeout: 5000
            cache:
              expire: 1000*60*60*2
              delay: 200
        - search: (^4|^5) 
          searchin: status 
          action: return
          return:
            body: The GateWay is down!
            status: 503

    - rule: ^https:\/\/cdn\.jsdelivr\.net
      transform_rules:
        - search: _
          replace:
          - _
          - https://fastly.jsdelivr.net
          - https://gcore.jsdelivr.net
          - https://test1.jsdelivr.net
          action: fetch
          fetch:
            status: 200
            engine: parallel
            preflight: false
            timeout: 5000
            cache:
              expire: 1000*60*60*24
              delay: 200
